### ISSUE TITLE
请问是否有人无法签到?

### ISSUE THREAD

**Issue by wxchil** [akinlau/glados_checkin#2]
提示如下,能够获取到天数,token没有失效,token即使重新抓取,仍旧提示token error
签到结果：oops, token error
剩余天数：33
<img width="336" alt="image" src="https://github.com/akinlau/glados_checkin/assets/44988562/fe9c9842-58d9-49a1-a500-fd01f67e2a6e">

**Comment by akinlau** [comment]
前段时间我的也有十几天没签到，后面重新拿了cookie就可以了

**Comment by wxchil** [comment]
> 前段时间我的也有十几天没签到，后面重新拿了cookie就可以了

是的,之前有过不签到的情况,当时应该是cookie过期,然后好像也不推送了,但是今天的情况是:新抓的cookie也出现错误

cookie的格式是"koa:sess=123456789;koa:sess.sig=abcdefg"

![image](https://github.com/akinlau/glados_checkin/assets/44988562/85c07f64-690a-4d1c-8355-8b93018c1f71)

**Comment by akinlau** [comment]
已经修复了，glados修改了token的值，你可以再试一下

**Comment by wxchil** [comment]
> 已经修复了，glados修改了token的值，你可以再试一下

非常感谢,已可正常使用!
